# Parameters for your particle filter

motion_params:
  vel_std:    0.05
  alpha_std:  0.5
  x_std:      0.05
  y_std:      0.05
  theta_std:  0.05

sensor_params:
  hit_std:    1.0
  z_hit:      0.5
  z_short:    0.05
  z_max:      0.05
  z_rand:     0.5
